### ISSUE TITLE
I added a new probe to support multi columns and multi rows from jdbc datasource 

### ISSUE THREAD

**Issue by wuzh** [fbacchella/jrds#28]
the probe class is  jrds.probe.jdbc.PowerJdbcProbe
and the probe desc is 
<probedesc>
    <name>DaasNodePerf</name>
    <probeName>DaasNodePerf</probeName>
    <probeClass>jrds.probe.jdbc.PowerJdbcProbe</probeClass>
    <specific name="query">SHOW @@datanode</specific>
    <specific name="keyAndValuePairs">NAME;EXECUTE;ACTIVE</specific>
    
    <ds>
        <dsName>EXECUTE</dsName>
        <dsType>counter</dsType>
        
        
    </ds>
    <ds>
        <dsName>ACTIVE</dsName>
        <dsType>gauge</dsType>
        
        
    </ds>
    <graphs>
        <name>DataNodeFluxGraph</name>
        <name>DataNodeConPoolGraph</name>
    </graphs>
</probedesc>

for the given table as follows 

NAME                    EXECUTE                     ACTIVE    

datanode1                     2                               10
datanode2                     4                                20

the probe will dynamic create RRD  DSs like follows:

key                                   value

---

datanode1.EXECUTE              2
datanode1.ACTIVE                 10
datanode2.EXECUTE              4
datanode2.ACTIVE                 20

and the probe also dynamic create RRD  Graphs of the follow names:

DataNodeFluxGraph.datanode1.EXECUTE
DataNodeFluxGraph.datanode2.EXECUTE
DataNodeConPoolGraph.datanode1.ACTIVE  
DataNodeConPoolGraph.datanode2.ACTIVE                 

the url of graph is like this :
http://localhost:8080/jrds/graph/localdaas/DataNodeFluxGraph_dn_1.EXECUTE?probe=daasnodeperf

**Comment by fbacchella** [comment]
Useless without a real pull request.
