### ISSUE TITLE
ApacheStatusDetails cannot listen to port 443

### ISSUE THREAD

**Issue by panthony** [fbacchella/jrds#44]
I tried to listen to the port 443 with the ApacheStatusDetails:
```xml
<probe type="ApacheStatusDetails">
    <attr name="port">443</attr>
</probe>
```
But it won't work because it will try to retrieve apache's status using the HTTP procotol when HTTPS is required in this case.

**Comment by fbacchella** [comment]
Done in commit a5df227269274d4dae85fb75d5f65092a560b7bd
