### ISSUE TITLE
Specifying a wrong -DpropertiesFile should warn the user / abort jrds

### ISSUE THREAD

**Issue by Kegeruneku** [fbacchella/jrds#62]
I tried to install a standalone jrds by following http://jrds.fr/installunix , but specified a -DpropertiesFile that was not here (typo).

The interface started happily:
```
ERROR - [jrds.HostsList] Probes directory not configured, can't configure
INFO - Application jrds started
^C
INFO - Application jrds will stop
INFO - Average wait time: NaN ms
INFO - Application jrds stopped
```

With only a "minor looking" error at the start, but a completely empty (but usable) web interface.

It might be a good idea to throw an error if at the start some necessary properties are not set properly, or if the declared properties (either coming from the file I gave or from the defaults) point to non existing directories?

Thanks!

**Comment by fbacchella** [comment]
Done in commit a811d92c7dac5ea585000e6114ea8536280cd0b0
