### ISSUE TITLE
Unit type is not returned by the graphdesc service

### ISSUE THREAD

**Issue by fthevenet** [fbacchella/jrds#69]
The graphdesc service (i.e.: http://localhost:8080/graphdesc?id=1755186310) that returns the description of a graph does not seem to return the unit type (typically "SI" or "binary") as part of its XML response.

The graphdesc DTD (https://github.com/fbacchella/jrds/blob/master/dtd/graphdesc.dtd) suggests that this piece of information _could_ be part of the XML response, in the form of a element called "unit", populated with either "SI", "binary and the unit's arithmatical's base as an int, but I have never seen it present in my tests.

**Comment by fbacchella** [comment]
It should be better now.

**Comment by fthevenet** [comment]
I'm having an other issue with the latest build (I got it from http://jrds.fr/build/jrds.tar.gz).
When starting jrds, I get the following error:
`ERROR - [localhost/processor1] Store c:\jrds\probe\localhost\processor1.rrd unusable: java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: c:\jrds\probe\localhost\processor1.rrd` for all declared probes.

This happens regardless of whether there are existing rrd files or if JRDS needs to recreate new rrds.

**Comment by fbacchella** [comment]
I changed the way backend are managed in rrd4j, it doesn't like the \ in windows path. I need to manage that.

**Comment by fbacchella** [comment]
It should be ok now: [rrd4j's commit](https://github.com/rrd4j/rrd4j/commit/05e0c18b899edfcd6025705d7f11eaea8265cdf3)
