### ISSUE TITLE
Data stores produced by RPN operations do not have a persistent name

### ISSUE THREAD

**Issue by fthevenet** [fbacchella/jrds#70]
The names of data storse generated through RPN functions are not stable across JRDSruntime sessions (i.e. they change each time JRDS is restarted).

Since the name of the data store is the only element that allow to identify which column in the csv returned by the download service corresponds to which store, this makes it quite tricky for applications that uses this service to persist their state or configurations across runtime sessions.

**Comment by fbacchella** [comment]
Should be done in commit a04370d472f07d44b6b162241e33f9d6e328df38

**Comment by fthevenet** [comment]
It seems to have done the trick, thanks!
